version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "xchen-node-hello-world"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-19khnfxmpduf4"
s3_prefix = "xchen-node-hello-world"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
